# Generated by Django 5.2.13 on 2026-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('travel_date', models.DateField()),
                ('num_people', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'Bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creator_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Revenue',
                'managed': True,
            },
        ),
    ]
