# Generated by Django 5.2.13 on 2026-04-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour'),
        ),
    ]
