# Generated by Django 6.0.4 on 2026-04-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprecord',
            options={'managed': False},
        ),
    ]
